---
title: "Geospatial Analysis with sf"
author: "Masha Monakhova"
date: "2023-03-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r}
library(sf)
library(ggplot2)
library(scales)
library(leaflet)
library(dplyr)
library(ggmap)
```

## Read data

```{r}
ak_regions <- read_sf("data/ak_regions_simp.shp")
```

```{r}
plot(ak_regions)
```

```{r}
class(ak_regions)
```

```{r}
ak_regions_3338 <- ak_regions %>%
  st_transform(crs = 3338)

st_crs(ak_regions_3338)
```

## sf & the tidyverse

```{r}
ak_regions_3338 %>%
  select(region)
```

```{r}
ak_regions_3338 %>%
  filter(region == "Southeast")
```

## spatial joins

```{r}
pop <- read.csv("data/alaska_population.csv")
```

## make "pop" an sf object using `st_as_sf()`

```{r}
pop_4326 <- st_as_sf(pop,
                    coords = c("lng", "lat"),
                    crs = 4326,
                    remove = FALSE)

head(pop_4326)
```

## assign each city to a region using `st_join()`

```{r}
pop_joined <- st_join(pop_4326, ak_regions_3338, join = st_within)
```

```{r}
pop_3338 <- st_transform(pop_4326, crs = 3338)
```

```{r}
pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)
head(pop_joined)
```

## calculate the total population per region using `group_by()`

```{r}
pop_region <- pop_joined %>%
  as.data.frame() %>%
  group_by(region) %>%
  summarize(total_pop = sum(population))
head(pop_region)
```

```{r}
pop_region_3388 <- left_join(ak_regions_3338, pop_region, by = "region")
head(pop_region_3388)
```

```{r}
plot(pop_region_3388["total_pop"])
```

```{r}
pop_mgmt_3388 <- pop_region_3388 %>%
  group_by(mgmt_area) %>%
  summarize(total_pop = sum(total_pop), do_union = FALSE)
plot(pop_mgmt_3388["total_pop"])
```

## writing spatial data as a file using `write_sf()`

```{r}
write_sf(pop_region_3388, "data/ak_regions_population.shp", delete_layer = TRUE)
```

## visualizing using `ggplot()`

```{r}
ggplot(pop_region_3388) +
  geom_sf(aes(fill = total_pop))+
  theme_bw()+
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high =  "firebrick", labels = comma)
```

```{r}
rivers_3338 <- read_sf("data/ak_rivers_simp.shp")
st_crs(rivers_3338)
```

```{r}
ggplot() +
  geom_sf(data = pop_region_3388, aes(fill = total_pop)) +
  geom_sf(data = rivers_3338, aes(size = StrOrder), color = "black") +
  geom_sf(data = pop_3338, aes(), size = .5) +
  scale_size(range = c(0.01, 0.2), guide = F) +
  theme_bw() +
  labs(fill = "Total Population") +
  scale_fill_continuous(low = "khaki", high =  "firebrick", labels = comma)
```

## Incorporate base maps into static maps using `ggmamp`

```{r}
pop_3857 <- pop_3338 %>%
  st_transform(crs = 3857)

# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
```

```{r}
bbox <- c(-170, 52, -130, 64) #roughly southern alaska
ak_map <- get_stamenmap(bbox, zoom = 4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)
```

```{r}
ggmap(ak_map_3857)+
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F)+
  scale_color_continuous(low = "khaki", high = "firebrick", labels = comma)
```

## interactive maps with leaflet

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
```

```{r}
pop_region_4326 <- pop_region_3388 %>%
  st_transform(crs = 4326)
```

```{r}
epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = "gray",
                    weight = 1)
m
```
```{r}
pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")
```

```{r}
pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1) %>% 
        addCircleMarkers(data = pop_4326,
                         lat = ~lat,
                         lng = ~lng,
                         radius = ~log(population/500), # arbitrary scaling
                         fillColor = "gray",
                         fillOpacity = 1,
                         weight = 0.25,
                         color = "black",
                         label = ~paste0(pop_4326$city, ", population ", comma(pop_4326$population))) %>%
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")

m
```

